name: flutter_confusion_matrix
description: "Package for creating and visualizing Confusion Matrices with a customizable heatmap."
version: 0.0.2
repository: https://github.com/Netesh5/flutter_confusion_matrix/tree/main

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

